services:
  redis:
    image: redis:7
    container_name: redis
    ports:
      - "6379:6379"
    networks:
      - loja-network
    volumes:
      - redis-data:/data

volumes:
  redis-data:

networks:
  loja-network:
    external: true
