services:
  postgres:
    image: postgres:15
    container_name: loja_postgres
    environment:
      POSTGRES_DB: sistema_loja
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: admin123
    ports:
      - "5438:5432"
    volumes:
      - ./data/postgres:/var/lib/postgresql/data
      - ./init:/docker-entrypoint-initdb.d
